version: '3.8'

services:  

  tackletickets:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8003"
    volumes:
      - .:/app
    ports:
      - "8003:8003"
    depends_on:
      - redis

  worker:
    build: ./worker
    command: celery -A ticketting worker --loglevel=info
    volumes:
      - ./worker:/app
    depends_on:
      - redis

  beat:
    build: ./worker
    command: celery -A ticketting beat --loglevel=info
    volumes:
      - ./worker:/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
