# Generated by Django 4.2.2 on 2023-07-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ussdrequest',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='ussdrequest',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
