# Generated by Django 4.2.2 on 2023-08-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_bankaccounts_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccounts',
            old_name='User',
            new_name='user',
        ),
    ]
