# Generated by Django 4.2.2 on 2023-08-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ussdrequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
